[package]
name = "photo_frame"
version = "0.1.0"
authors = ["Sam Nalty"]
edition = "2018"

[dependencies]
gtk = "0.9.2"
atk = "0.9.0"
gdk-pixbuf = "0.9.0"
gio = "0.9.1"
rocket = "0.4.6"
glib = "0.10.3"
futures = "0.3.8"
flame = "0.2.2"
flamer = "0.3"
rusqlite = "0.24.2"
rocket-multipart-form-data = "0.9.6"
clap = "2.33.3"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
mime = "0.3.16"

[[bin]]
name = "my_bin"
path = "main.rs"

[[bin]]
name = "load-examples"
path = "load_examples.rs"